version: '3.8'

services:
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:3000
  #     - MONGODB_URI=mongodb://mongo:27017/myapp
  #     - REDIS_URL=redis://redis:6379
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    command: redis-server --notify-keyspace-events KEA
    ports:
      - "6379:6379"

volumes:
  mongo_data: